# Generated by Django 3.0.7 on 2021-06-21 18:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(help_text='unique id.', max_length=255, primary_key=True, serialize=False)),
                ('published_at', models.DateField(help_text='The date and time that the video was published. Note thatthis time might be different than the time that the video was uploaded.')),
                ('title', models.CharField(help_text="stores the video's title.", max_length=500)),
                ('description', models.CharField(help_text="stores the video's description.", max_length=5000)),
                ('thumbnails_info', django.contrib.postgres.fields.jsonb.JSONField(help_text='A map of thumbnail images associated with the video.For each object in the map, the key is the name of the thumbnailimage, and the value is an object that contains other informationabout the thumbnail.')),
                ('channel_id', models.CharField(help_text='The ID that YouTube uses to uniquely identify the channel that the video was uploaded to.', max_length=100)),
                ('channel_title', models.CharField(help_text='Channel title for the channel that the video belongs to.', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
