# Generated by Django 3.0.7 on 2021-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(help_text='The date and time that the video was published. Note thatthis time might be different than the time that the video was uploaded.'),
        ),
    ]
