# Generated by Django 3.0.7 on 2021-06-22 05:56

import apps.youtube.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20210621_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelManagers(
            name='videos',
            managers=[
                ('objects', apps.youtube.managers.BulkManager()),
                ('all_objects', apps.youtube.managers.BulkAllManager()),
            ],
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.CharField(blank=True, help_text="stores the video's description.", max_length=5000, null=True),
        ),
    ]
